### ISSUE TITLE
Separate firs and last names in Flight Detail page to enable sorting by first or last names

### ISSUE THREAD

**Issue by PaulaNelson** [shmakes/hf-basic#137]

**Comment by shmakes** [comment]
Do you ever really sort by first name or just wish you could sort by last name?
I modified the sort so that it will sort by last name even though it displays first and last name, so give it a try.

Let me know if this solve the issue for you.
(If not, I will break into two columns, but that uses up more space on an already crowded screen.)

**Comment by PaulaNelson** [comment]
This should work - let's try it.  I do sort by first name sometimes ....but
could do that through a dump to excel.



On Wed, Nov 25, 2015 at 2:06 PM, Steve Schmechel <notifications@github.com>
wrote:

> Do you ever really sort by first name or just wish you could sort by last
> name?
> I modified the sort so that it will sort by last name even though it
> displays first and last name, so give it a try.
>
> Let me know if this solve the issue for you.
> (If not, I will break into two columns, but that uses up more space on an
> already crowded screen.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shmakes/hf-basic/issues/137#issuecomment-159717891>.
>



-- 
Paula Nelson
President
Stars and Stripes Honor Flight
262-305-6424

**Comment by shmakes** [comment]
Closed by 9471dda6be1cb29c380379de6037244af474231a
