### ISSUE TITLE
Add "accommodations" to veterans and guardians

### ISSUE THREAD

**Issue by shmakes** [shmakes/hf-basic#179]
Room type (double queen, single king)
Start date
End Date

Banquette (yes, no)
Guest Name

Add to flight export.

**Comment by shmakes** [comment]
@midwesthonorflight  @bjbradl4
This is addressing this ticket and #207 

![image](https://user-images.githubusercontent.com/686667/93691821-6ee65b80-fab0-11ea-9323-6080dbc7dfc2.png)

**Comment by shmakes** [comment]
@midwesthonorflight 
Is the same info required on the guardian form or just on the veteran form?

**Comment by midwesthonorflight** [comment]
This is great Steve, thank you!  We would love it to also be on the
Guardians too.  Thank you!

One Final Tour with Honor,

*Aaron Van Beek* | President & Director


*Midwest Honor Flight*
PO Box 22 | Sioux Center, IA 51250
(712) 463-2020

www.midwesthonorflight.org
www.facebook.com/midwesthonorflight
www.instagram.com/midwesthonorflight


*This email is confidential and for the use of the intended recipient(s)
only. If you are not the intended recipient or you have received this email
in error, please notify the sender immediately and then delete this email
with all attachment(s). You must not use, disclose or distribute this email
or the information contained in or attached to this email without the
author's prior permission. We have taken precautions to minimize the risk
of transmitting software viruses, but we advise you to carry out your own
virus checks on any attachment to this message. We cannot accept liability
for any loss or damage caused by software viruses.*

**Comment by shmakes** [comment]
Pushed to Lone Eagle branch
