### ISSUE TITLE
Online app emergency contact info

### ISSUE THREAD

**Issue by 3354sstt** [shmakes/hf-basic#180]
Emergency contact info entered into vet online app should go into Primary Emergency Contact fields vs Alternate.

**Comment by shmakes** [comment]
Christy,

There was a reason we choose to fill the alternate in instead of the
emergency contact. Do you remember?
Lack of email on emergency contact might have been part of it, but it might
have been to get contact info for mail call.
I can't remember right now.

There are more than a so many on the waitlist like this already, do we want
to switch now?
What would be the way to make it consistent for everyone?

**Comment by shmakes** [comment]
I have no idea if we just overlooked this or there was a reason. I think we
can switch it moving forward.  The waitlist is going to continue to grow.

Thanks!

**Comment by shmakes** [comment]
Closed by https://github.com/shmakes/hf-app-review/issues/11 and #240

**Comment by 3354sstt** [comment]
Created a new online app from the website and emergency contact info ported to proper location now and there is only one emergency contact being loaded.
Shouldn't the heading of this now be "Emergency Contact" vs ALTERNATE EMERGENCY CONTACT ?

**Comment by shmakes** [comment]
Jim,
The code is not in production yet so you will not see the changes from the
website.
Go to the "Review Applications for Test" link and you will find some
veteran apps waiting for review.
Pick on and change the name to something unique (if needed) then edit the
application to get the emergency contact info the way you want.
Then mark the app "Accepted" and save.
You should see a popup that says it was added to the waitlist.
Then goto the "Test Database" and find the application you just added.
The emergency contact info should be in the correct spot.

**Comment by 3354sstt** [comment]
Yeah I was looking in the prod dB, good point.
Looks like it works as advertised
