### ISSUE TITLE
Include vets marked Not Flying in total vet flight count

### ISSUE THREAD

**Issue by 3354sstt** [shmakes/hf-basic#181]
Example in Sept we have Kenneth Butterfield meeting in DC. He is marked Not Flying with red strikethrough. 
He should probably be included in total vet count.

**Comment by shmakes** [comment]
He will be in the bus assignment count but not the flight assignment
because he's not flying. He will also be one of the rows in the veteran
flight export.

I believe that was the whole point of doing this change was to allow him to
be in the database but not overestimate the number of seats used on the
plane.

I guess I'm not sure what the concern is. where do you think he was missing
other than the spot where it was causing a problem?

**Comment by 3354sstt** [comment]
Not a concern really. We just don’t have an exact count of vets on that view but we rarely have vets meet in DC so it’s a non-issue. Close it.
